[package]
name = "EquinoxV2"
version = "0.0.2"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet" }

[addresses]
equinox_addr = "0x38cf30ab98f13466c60df462ac3e57b6391d6a3c3f22c34bea4e4f3386eafd96"