[package]
name = "EquinoxV3"
version = "0.0.3"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet" }

[addresses]
equinox_addr = "0x1b5957414b227d9fedd6015c2b53e648166cc552b6b9747a68c496c5b45086f7"